/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-12-01 19:14:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/hyuck/Spring/mini/planeproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PlaneTripProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/hyuck/Spring/mini/planeproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PlaneTripProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668733234630L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>STN</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	body { background-color : #F6F6F6;}\r\n");
      out.write("	#f_banner, #s_banner { width: 1200px; margin: 0 auto; border: 1px solid #F6F6F6; text-align: center; justify-content: center;}\r\n");
      out.write("    #f_banner { margin-top : 0px;}\r\n");
      out.write("    b { font-size: 1.5em;}\r\n");
      out.write("    #route { font-family: 'Jua', sans-serif;margin-top: 25px;}\r\n");
      out.write("    h2 { text-align: left; margin-top: 25px;font-family: 'Noto Sans KR', sans-serif;}\r\n");
      out.write("    sup { font-size: 1em;}\r\n");
      out.write("    #main_banner { width: 1700px;margin: 0 auto; border: 1px solid #F6F6F6; text-align: center; justify-content: center; margin-top : -50px}\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    a:link { color: black; text-decoration: none;}\r\n");
      out.write("    a:visited { color: black; text-decoration: none;}\r\n");
      out.write("    a:hover { color: black; text-decoration: none;}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("        #container{ width: 100%; height: 100%; text-align: center;justify-content: center;}\r\n");
      out.write("        /*메뉴 위치선정 */\r\n");
      out.write("        #category_menu nav{ display: inline-block; text-align: center;}\r\n");
      out.write("        .line1{ position: absolute; top: 0px; left: 8.25%; border-left: 1px solid #f2f2f2; width: 16.5%; height: 280px;}\r\n");
      out.write("        .line2{ position: absolute; top: 0px; left: 24.75%; border-left: 1px solid #f2f2f2; width: 16.5%; height: 280px;}\r\n");
      out.write("        .line3{ position: absolute; top: 0px; left: 41.25%; border-left: 1px solid #f2f2f2; width: 16.5%; height: 280px;}\r\n");
      out.write("        .line4{ position: absolute; top: 0px; left: 57.75%; border-left: 1px solid #f2f2f2; width: 16.5%; height: 280px;}\r\n");
      out.write("        .line5{ position: absolute; top: 0px; left: 74.25%; border-left: 1px solid #f2f2f2; width: 16.5%; height: 280px;\r\n");
      out.write("            border-right: 1px solid #f2f2f2;}\r\n");
      out.write("        /*아래 반투명 화면*/\r\n");
      out.write("        #category_black{ width: 100%; height: 100%; background-color: black; opacity: 0.5;}\r\n");
      out.write("\r\n");
      out.write("        /*티케팅 창*/\r\n");
      out.write("        #ticketing{ width: 1200px; margin-top: 20px; display: inline-block;}\r\n");
      out.write("        #ticketing_box{ width: 100%; height: 220px; box-shadow: 0 0 4px #c8c8c8;\r\n");
      out.write("            border-radius: 10px; background-color : white;}\r\n");
      out.write("        #way ul, #way li{ list-style: none;}\r\n");
      out.write("        #way li{ float: left; margin-right: 30px; margin-top: 20px; font-weight: light;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-size: medium;}\r\n");
      out.write("        #round{ color: #ff5000; border-bottom: #ff5000 2px solid; text-decoration: none; margin-left : 125px}\r\n");
      out.write("        #oneway{ text-decoration: none; color: inherit; }\r\n");
      out.write("\r\n");
      out.write("        #form_div{clear: both; padding-top: 20px; text-align: left;}\r\n");
      out.write("        #starting_point{width: 270px; height: 50px; color: #8c8c8c; cursor: pointer; margin-left: 165px;\r\n");
      out.write("            border: none; border-bottom: solid #c8c8c8 1px; background-color:transparent; \r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: x-large;}\r\n");
      out.write("        #swap{ width: 30px; height: 30px; border: none; margin-left: 10px; margin-right: 10px;\r\n");
      out.write("            background: url( \"../../resources/images/arrow.png\") no-repeat; cursor: pointer; border-radius: 100%;}\r\n");
      out.write("        #arrive_point{width: 270px; height: 50px; color: #8c8c8c; cursor: pointer;\r\n");
      out.write("            border: none; border-bottom: solid #c8c8c8 1px; background-color:transparent;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: x-large;}\r\n");
      out.write("        #calendar_date{ width: 250px; height: 43px; margin-left: 20px; background-color:transparent;\r\n");
      out.write("            background-image: url(\"../../resources/images/calendar.png\"); background-repeat: no-repeat;\r\n");
      out.write("            background-size: 20px; background-position: left; cursor: pointer;\r\n");
      out.write("            border-style: none; border-bottom: solid #c8c8c8 1px;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: medium;}\r\n");
      out.write("        #person{ width: 270px; height: 43px; margin-top: 20px; background-color: transparent;\r\n");
      out.write("            background-image: url(\"../../resources/images/person.png\"); background-repeat: no-repeat;\r\n");
      out.write("            background-size: 20px; background-position: 10px center; cursor: pointer;\r\n");
      out.write("            border-style: none;  border-bottom: solid #c8c8c8 1px; margin-left: 165px;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: medium;}\r\n");
      out.write("        #serch{ width: 200px; height: 50px; margin-left: 400px; margin-top: 30px; cursor: pointer;\r\n");
      out.write("            background-color: #aaaaaa; color: white; border: none; border-radius: 5px;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: large;}\r\n");
      out.write("            \r\n");
      out.write("        /*출발지*/\r\n");
      out.write("        #starting_point_serch{ width: 950px; height: 400px; background-color: white;\r\n");
      out.write("            display: none; position: absolute; opacity: none; z-index: 2;\r\n");
      out.write("            top: 50%; left: 50%; transform: translate(-50%, -35%); box-shadow: 0 0 4px #c8c8c8;\r\n");
      out.write("            margin-top: 150px;}\r\n");
      out.write("        #dummy_serch{ width: 100%; height: 60px;}\r\n");
      out.write("        #dummy_serch_img{ width: 20px; height: 20px; float: left; cursor: pointer;\r\n");
      out.write("             margin-top: 25px; margin-left: 30px;}\r\n");
      out.write("        #dummy_serch input{ width: 830px; height: 40px; margin: 10px; float: left; border: none;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: large; outline: none;\r\n");
      out.write("            margin-top : 14px;}\r\n");
      out.write("        .close{ width: 20px; height: 20px; float: right; cursor: pointer;\r\n");
      out.write("            margin-top: 25px; margin-right: 25px;}\r\n");
      out.write("\r\n");
      out.write("        #starting_point_list1{ width: 20%; height: 330px; float: left; background-color: #f2f2f2}\r\n");
      out.write("        #starting_point_list1 ul { margin-left : -40px; margin-top : -5px; list-style: none;}\r\n");
      out.write("        #starting_point_list1 li{ width: 100%; height: 40px; padding-top: 15px;\r\n");
      out.write("            background-color: #f2f2f2;  border-bottom: #dcdcdc solid 1px;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: large;}\r\n");
      out.write("        #starting_point_list1 li:first-child{ background-color: white;}\r\n");
      out.write("\r\n");
      out.write("        #starting_point_list2{ width: 80%; height: 330px; float: right; background-color: white}\r\n");
      out.write("        #starting_point_list2 ul { margin-top : -5px; list-style: none;}\r\n");
      out.write("        #starting_point_list2 div{ width: 100%; height: 35px; text-align: left;\r\n");
      out.write("            padding-top: 5px; padding-left: 20px; cursor: pointer;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: large;}\r\n");
      out.write("        #starting_point_list2 div:first-child{ padding-top: 15px;}\r\n");
      out.write("        #starting_point_list2 li a{ color: #aaaaaa;}\r\n");
      out.write("\r\n");
      out.write("        /* 도착지 */\r\n");
      out.write("        #arrive_point_serch{ width: 950px; height: 400px; background-color: white; \r\n");
      out.write("            display: none; position: absolute; opacity: none; z-index: 2;\r\n");
      out.write("            top: 50%; left: 50%; transform: translate(-50%, -35%); box-shadow: 0 0 4px #c8c8c8;\r\n");
      out.write("            margin-top: 150px;}\r\n");
      out.write("        #arrive_point_list1{ width: 20%; height: 330px; float: left; background-color: #f2f2f2}\r\n");
      out.write("        #arrive_point_list1 ul { margin-left : -40px; margin-top : -5px;  list-style: none;}\r\n");
      out.write("        #arrive_point_list1 li{ width: 100%; height: 40px; padding-top: 15px;\r\n");
      out.write("            background-color: #f2f2f2;  border-bottom: #dcdcdc solid 1px;\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: large;}\r\n");
      out.write("        #arrive_point_list1 li:first-child{ background-color: white;}\r\n");
      out.write("        #arrive_point_list2{ width: 80%; height: 330px; float: right; background-color: white}\r\n");
      out.write("        #arrive_point_list2 ul { margin-top : -5px;  list-style: none;}\r\n");
      out.write("        #arrive_point_list2 div{ width: 100%; height: 35px; text-align: left;\r\n");
      out.write("            padding-top: 5px; padding-left: 20px; cursor: pointer; \r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif; font-weight: bold; font-size: large;}\r\n");
      out.write("        #arrive_point_list2 div:first-child{ padding-top: 15px;}\r\n");
      out.write("        \r\n");
      out.write("        /* 날짜 선택(달력) */\r\n");
      out.write("        #calendar{ width: 950px; height: 400px; background-color: white; \r\n");
      out.write("            display: none; position: absolute; opacity: none; z-index: 2;\r\n");
      out.write("            top: 50%; left: 50%; transform: translate(-50%, -46%); box-shadow: 0 0 4px #c8c8c8;}\r\n");
      out.write("        #calendar .close{ position: absolute; top: 0%; right: 0%;}\r\n");
      out.write("        #cal1_div{ width: 50%; height: 100%; float: left;}\r\n");
      out.write("        #cal2_div{ width: 50%; height: 100%; float: left;}\r\n");
      out.write("        \r\n");
      out.write("        #cal_pre{ position: absolute; left: 2%; top: 43%; border: none; background: none;}\r\n");
      out.write("        #cal_next{ position: absolute; right: 2%; top: 43%; border: none; background: none; }\r\n");
      out.write("\r\n");
      out.write("        #cal1_year, #cal1_month{ position: absolute; font-size: large; font-weight: bold;}\r\n");
      out.write("        #cal1_year{left: 8%; top: 4%;}\r\n");
      out.write("        #cal1_month{left: 15%; top:4%;}\r\n");
      out.write("        #cal1 { display: flex; flex-wrap: wrap; width: 80%; margin-left: 13%; margin-top: 10%;}\r\n");
      out.write("        .asdf{ text-align: center; width: calc(100%/7); height: 50px; box-sizing: border-box;line-height: 3;\r\n");
      out.write("             border-radius: 3px; color: #c8c8c8 !important;}\r\n");
      out.write("        #cal1 > .date {text-align: center; width: calc(100%/7); height: 50px; box-sizing: border-box;line-height: 3; border-radius: 3px;} \r\n");
      out.write("        #cal1 > .date:nth-child(7n){color: blue;}\r\n");
      out.write("        #cal1 > .date:nth-child(7n+1){color: red;}\r\n");
      out.write("        \r\n");
      out.write("        #cal2_year, #cal2_month{ position: absolute; font-size: large; font-weight: bold;}\r\n");
      out.write("        #cal2_year{left: 55%; top: 4%;}\r\n");
      out.write("        #cal2_month{left: 62%; top:4%;}\r\n");
      out.write("        #cal2 { display: flex; flex-wrap: wrap; width: 80%; margin-left: 7%; margin-top: 10%;}\r\n");
      out.write("        #cal2 > .date {text-align: center; width: calc(100%/7); height: 50px; box-sizing: border-box;line-height: 3; border-radius: 3px; cursor: Z;} \r\n");
      out.write("        #cal2 > .date:nth-child(7n){color: blue;}\r\n");
      out.write("        #cal2 > .date:nth-child(7n+1){color: red;}\r\n");
      out.write("        #cal2 > .date2 {text-align: center; width: calc(100%/7); height: 50px; box-sizing: border-box;line-height: 3; border-radius: 3px; cursor: Z;} \r\n");
      out.write("        #cal2 > .date2:nth-child(7n){color: blue;}\r\n");
      out.write("        #cal2 > .date2:nth-child(7n+1){color: red;}\r\n");
      out.write("        \r\n");
      out.write("        #date_select{ width: 100px; height: 30px; position: absolute; bottom: 4%; left: 44.5%;\r\n");
      out.write("            border: none; background-color: #ff5000; color: white; font-family: 'Jua';}\r\n");
      out.write("\r\n");
      out.write("        /*인원수*/\r\n");
      out.write("        #personnel{  width: 950px; height: 300px; background-color: white; \r\n");
      out.write("            display: none; position: absolute; opacity: none; z-index: 2;\r\n");
      out.write("            top: 50%; left: 50%; transform: translate(-50%, -35%); box-shadow: 0 0 4px #c8c8c8; }\r\n");
      out.write("        #personnel img{ width: 30px; height: 30px; position: absolute; top: 10%; left: 47.5%;}\r\n");
      out.write("        #personnel_body input{ width: 30px; height: 30px; text-align: center;\r\n");
      out.write("            border: none; border-bottom: 1px solid #dcdcdc;}\r\n");
      out.write("        #personnel_body>div button{  width: 30px; height: 30px; border-radius: 100%; border: none; }\r\n");
      out.write("        #personnel_header{ height: 30%;}\r\n");
      out.write("        #personnel_header_left{ width: 50%; float: left; margin-top: 3%; font-family: 'Jua'}\r\n");
      out.write("        #personnel_header_right{ width: 50%; float: left; margin-top: 3%; font-family: 'Jua'}\r\n");
      out.write("        #p_start{ font-size: x-large;}\r\n");
      out.write("        #p_arrive{ font-size: x-large;}\r\n");
      out.write("        #personnel_body{ clear: both; width: 100%; height: 70%; }\r\n");
      out.write("        #personnel_body_left{ width: 33.33%; height: 100%; float: left;}\r\n");
      out.write("        #personnel_body_center{ width: 33.33%; height: 100%; float: left;}\r\n");
      out.write("        #personnel_body_right{ width: 33.33%; height: 100%; float: left;}\r\n");
      out.write("        .body_text_title{ margin-top: 10%; margin-left: 10%; text-align: left; }\r\n");
      out.write("        .body_text_content{ margin-top: 1%; margin-left: 10%; text-align: left; font-size: small;}\r\n");
      out.write("        #body_button_left{ position: absolute; left:18%; top: 45%;}\r\n");
      out.write("        #body_button_center{ position: absolute; left:51.33%; top: 45%;}\r\n");
      out.write("        #body_button_right{ position: absolute; left:84.66%; top: 45%;}\r\n");
      out.write("\r\n");
      out.write("        #select_personnel{ width: 150px; height: 40px; position: absolute; bottom: 6%; left: 41%;\r\n");
      out.write("            background-color: #ff5000; border: none; color: white; border-radius: 5px; \r\n");
      out.write("            font-family: 'Jua'; font-size: large;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 상단 웹페이지 스크립트 -->\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("        let way = 0;        //왕복 편도\r\n");
      out.write("        let flag = false;   //유효성검사\r\n");
      out.write("        let start = $(\".start\").get();\r\n");
      out.write("        let arrive = $(\".arrive\").get();\r\n");
      out.write("        //날짜\r\n");
      out.write("        var CDate = new Date();\r\n");
      out.write("        let today = new Date();\r\n");
      out.write("        let day = [\"일\", \"월\", \"화\", \"수\", \"목\", \"금\", \"토\"];\r\n");
      out.write("        let e_target1;  //첫번째 클릭한 날짜 오브젝트 저장\r\n");
      out.write("        let e_target2;\r\n");
      out.write("        let text1;      //출발날짜 저장파일\r\n");
      out.write("        let text2;      //도착날짜 저장\r\n");
      out.write("        let textd1;     //.찍혀있는 날짜\r\n");
      out.write("        let textd2;\r\n");
      out.write("        let date_flag = 0;\r\n");
      out.write("\r\n");
      out.write("        let dtemp = 0;\r\n");
      out.write("        //여행 날짜 기본설정\r\n");
      out.write("        $(\"#calendar_date\").val(today.getFullYear() + \".\" + (today.getMonth()+1) + \".\" + today.getDate() + \" ~ \" + today.getFullYear() + \".\" + (today.getMonth()+1) + \".\" + today.getDate());\r\n");
      out.write("       \r\n");
      out.write("        //왕복, 편도(왕복일때 way=0, 편도일때 way=1)\r\n");
      out.write("        $(\"#round\").click(function(e){\r\n");
      out.write("            way=0;\r\n");
      out.write("            $(\"#round\").css(\"color\",\"#ff5000\").css(\"border-bottom\", \"#ff5000 2px solid\");\r\n");
      out.write("            $(\"#oneway\").css(\"color\", \"black\").css(\"border-bottom\", \"none\");\r\n");
      out.write("        })\r\n");
      out.write("        $(\"#oneway\").click(function(e){\r\n");
      out.write("            way=1;\r\n");
      out.write("            $(\"#oneway\").css(\"color\",\"#ff5000\").css(\"border-bottom\", \"#ff5000 2px solid\");\r\n");
      out.write("            $(\"#round\").css(\"color\", \"black\").css(\"border-bottom\", \"none\");\r\n");
      out.write("        })\r\n");
      out.write("        //출발지 입력창\r\n");
      out.write("        $(\"#starting_point\").click(function(e){\r\n");
      out.write("            $(\"#starting_point_serch\").css(\"display\", \"inline-block\");\r\n");
      out.write("            $(\"#arrive_point_serch\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#calendar\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#personnel\").css(\"display\", \"none\");\r\n");
      out.write("        })\r\n");
      out.write("        for(let i = 0; i < start.length; i++){\r\n");
      out.write("            $(start[i]).click(function(e){\r\n");
      out.write("                $(\"#starting_point\").val(start[i].innerHTML);\r\n");
      out.write("                $(\"#departPointId\").val(i+1);	//공항의 id를 저장\r\n");
      out.write("                $(\"#starting_point\").css(\"color\", \"black\");\r\n");
      out.write("                $(\"#starting_point_serch\").css(\"display\", \"none\");\r\n");
      out.write("                flag=true;\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //도착지 입력창\r\n");
      out.write("        $(\"#arrive_point\").click(function(e){\r\n");
      out.write("            if(!flag){\r\n");
      out.write("                alert(\"도착지를 입력해주세요.\")\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("                $(\"#arrive_point_serch\").css(\"display\", \"inline-block\");\r\n");
      out.write("            	$(\"#starting_point_serch\").css(\"display\", \"none\");\r\n");
      out.write("                $(\"#calendar\").css(\"display\", \"none\");\r\n");
      out.write("                $(\"#personnel\").css(\"display\", \"none\");\r\n");
      out.write("        })\r\n");
      out.write("        for(let i = 0; i < arrive.length; i++){\r\n");
      out.write("            $(arrive[i]).click(function(e){\r\n");
      out.write("                $(\"#arrive_point\").val(arrive[i].innerHTML);\r\n");
      out.write("                $(\"#arrivedPointId\").val(i+1);	//공항의 id를 저장\r\n");
      out.write("                $(\"#arrive_point\").css(\"color\", \"black\");\r\n");
      out.write("                $(\"#arrive_point_serch\").css(\"display\", \"none\");\r\n");
      out.write("            })\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //출발지 도착지 스왑\r\n");
      out.write("        $(\"#swap\").click(function(){\r\n");
      out.write("            if($(\"#arrive_point\").val() == \"도착지\"){\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            else{ \r\n");
      out.write("                let temp = $(\"#arrive_point\").val();\r\n");
      out.write("                let temp2 = $(\"#arrivedPointId\").val();\r\n");
      out.write("                $(\"#arrive_point\").val($(\"#starting_point\").val());\r\n");
      out.write("                $(\"#arrivedPointId\").val($(\"#departPointId\").val());\r\n");
      out.write("                $(\"#starting_point\").val(temp);\r\n");
      out.write("                $(\"#departPointId\").val(temp2);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        //달력 만들기\r\n");
      out.write("        $.create_cal = function (num) {\r\n");
      out.write("	        let htmlDates = ''; \r\n");
      out.write("            let prevLast = new Date(CDate.getFullYear(), CDate.getMonth(), 0); //지난 달의 마지막 날 \r\n");
      out.write("            let thisFirst = new Date(CDate.getFullYear(), CDate.getMonth(), 1); //이번 달의 첫쨰 날\r\n");
      out.write("            let thisLast = new Date(CDate.getFullYear(), CDate.getMonth() + 1, 0); //이번 달의 마지막 날\r\n");
      out.write("            const dates = []; \r\n");
      out.write("\r\n");
      out.write("            $(\"#cal1_year\").html(CDate.getFullYear() + \"년\");\r\n");
      out.write("            $(\"#cal1_month\").html((CDate.getMonth() + 1) + \"월\");\r\n");
      out.write("            if((CDate.getMonth() + 2) == 13){\r\n");
      out.write("                $(\"#cal2_year\").html((CDate.getFullYear() + 1) + \"년\");\r\n");
      out.write("                $(\"#cal2_month\").html( \"1월\");\r\n");
      out.write("            }\r\n");
      out.write("            else{\r\n");
      out.write("                $(\"#cal2_year\").html(CDate.getFullYear() + \"년\");\r\n");
      out.write("                $(\"#cal2_month\").html((CDate.getMonth() + 2) + \"월\");\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            if(thisFirst.getDay()!=0){ \r\n");
      out.write("                for(let i = 0; i < thisFirst.getDay(); i++){\r\n");
      out.write("                    dates.unshift(prevLast.getDate()-i); // 지난 달 날짜 채우기\r\n");
      out.write("                } \r\n");
      out.write("            } \r\n");
      out.write("            for(let i = 1; i <= thisLast.getDate(); i++){\r\n");
      out.write("                    dates.push(i); // 이번 달 날짜 채우기 \r\n");
      out.write("            } \r\n");
      out.write("            for(let i = 1; i <= 13 - thisLast.getDay(); i++){ \r\n");
      out.write("                    dates.push(i); // 다음 달 날짜 채우기 (나머지 다 채운 다음 출력할 때 42개만 출력함)\r\n");
      out.write("            } \r\n");
      out.write("            \r\n");
      out.write("            //inner html에 데이터 잔뜩 집어넣기\r\n");
      out.write("            if(num == 1){\r\n");
      out.write("                for(let i = 0; i < 42; i++){\r\n");
      out.write("                    if(i < thisFirst.getDay()){\r\n");
      out.write("                        htmlDates += '<div class=\"asdf\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }else if(today.getDate() > dates[i] && today.getMonth()==CDate.getMonth() && today.getFullYear()==CDate.getFullYear()){\r\n");
      out.write("                        htmlDates += '<div class=\"asdf\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }else if(today.getDate()==dates[i] && today.getMonth()==CDate.getMonth() && today.getFullYear()==CDate.getFullYear()){\r\n");
      out.write("                        htmlDates += '<div id=\"date_'+dates[i]+'\" class=\"date\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }else if(i >= thisFirst.getDay() + thisLast.getDate()){\r\n");
      out.write("                        htmlDates += '<div class=\"asdf\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }else{\r\n");
      out.write("                        htmlDates += '<div id=\"date_'+dates[i]+'\" class=\"date\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            else if(num == 2){\r\n");
      out.write("                for(let i = 0; i < 42; i++){\r\n");
      out.write("                    if(i < thisFirst.getDay()){\r\n");
      out.write("                        htmlDates += '<div class=\"asdf\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }else if(today.getDate() > dates[i] && today.getMonth()==CDate.getMonth() && today.getFullYear()==CDate.getFullYear()){\r\n");
      out.write("                        htmlDates += '<div class=\"asdf\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }else if(today.getDate()==dates[i] && today.getMonth()==CDate.getMonth() && today.getFullYear()==CDate.getFullYear()){\r\n");
      out.write("                        htmlDates += '<div id=\"date2_'+dates[i]+'\" class=\"date\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }else if(i >= thisFirst.getDay() + thisLast.getDate()){\r\n");
      out.write("                        htmlDates += '<div class=\"asdf\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }else{\r\n");
      out.write("                        htmlDates += '<div id=\"date2_'+dates[i]+'\" class=\"date2\">'+dates[i]+'</div>'; \r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            // div에 넣기\r\n");
      out.write("            return htmlDates;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //뒷배경 지우기 함수\r\n");
      out.write("        $.clear = function() {\r\n");
      out.write("            $(\".date\").css(\"background-color\", \"\");\r\n");
      out.write("            $(\".date\").css(\"color\", \"\");\r\n");
      out.write("            $(\".date2\").css(\"background-color\", \"\");\r\n");
      out.write("            $(\".date2\").css(\"color\", \"\");\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        //앞 달력 이벤트\r\n");
      out.write("        $(document).on(\"click\", \".date\", function(e){\r\n");
      out.write("            if(dtemp == 0){\r\n");
      out.write("                $.clear();\r\n");
      out.write("                $(e.target).css(\"background-color\", \"red\");\r\n");
      out.write("                $(e.target).css(\"color\", \"white\");\r\n");
      out.write("\r\n");
      out.write("                console.log(e.target);\r\n");
      out.write("                e_target1 = e.target;\r\n");
      out.write("                dtemp = 1;\r\n");
      out.write("            }\r\n");
      out.write("            else if(dtemp == 1){\r\n");
      out.write("                if(e_target1.className == \"date\" && ((Number)(e_target1.textContent)) > ((Number)(e.target.textContent))){\r\n");
      out.write("                    alert(\"일정을 확인해주세요\");\r\n");
      out.write("                    $.clear();\r\n");
      out.write("                }\r\n");
      out.write("                else if(e_target1.className == \"date2\"){\r\n");
      out.write("                    alert(\"일정을 확인해주세요\");\r\n");
      out.write("                    $.clear();\r\n");
      out.write("                }\r\n");
      out.write("                else{\r\n");
      out.write("                    e_target2 = e.target;\r\n");
      out.write("                    $(e.target).css(\"background-color\", \"red\");\r\n");
      out.write("                    $(e.target).css(\"color\", \"white\");\r\n");
      out.write("                    for(let i = ((Number)(e_target1.textContent)) + 1; i < e.target.textContent; i++){\r\n");
      out.write("                        $(\"#date_\"+i).css(\"background-color\", \"#FFDDDD\");\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                dtemp = 0;\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        //뒤 달력 이벤트\r\n");
      out.write("        $(document).on(\"click\", \".date2\", function(e){\r\n");
      out.write("            if(dtemp == 0){	//아무것도 선택하지 않은 상태일때\r\n");
      out.write("                $.clear();\r\n");
      out.write("                $(e.target).css(\"background-color\", \"red\");\r\n");
      out.write("                $(e.target).css(\"color\", \"white\");\r\n");
      out.write("                \r\n");
      out.write("                e_target1 = e.target;\r\n");
      out.write("                dtemp = 1\r\n");
      out.write("            }\r\n");
      out.write("            else if(dtemp == 1){	//날짜한개를 선택한 상태일때\r\n");
      out.write("            	//날짜\r\n");
      out.write("                if(e_target1.className == \"date2\" && ((Number)(e_target1.textContent)) > ((Number)(e.target.textContent))){\r\n");
      out.write("                    alert(\"두번째 선택하는 날짜는 첫번째 날짜보다 이전일 수 없습니다.\");\r\n");
      out.write("                    $.clear();\r\n");
      out.write("                }\r\n");
      out.write("                else{	//정상적으로 날짜를 선택했을때\r\n");
      out.write("                    e_target2 = e.target;\r\n");
      out.write("                    $(e.target).css(\"background-color\", \"red\");\r\n");
      out.write("                    $(e.target).css(\"color\", \"white\");\r\n");
      out.write("                    if(e_target1.className == \"date\"){\r\n");
      out.write("                        for(let i = ((Number)(e_target1.textContent)) + 1; i < 32; i++){\r\n");
      out.write("                            $(\"#date_\"+i).css(\"background-color\", \"#FFDDDD\");\r\n");
      out.write("                            for(let j = 1; j < e.target.textContent; j++){\r\n");
      out.write("                                $(\"#date2_\"+j).css(\"background-color\", \"#FFDDDD\");\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    else{\r\n");
      out.write("                        for(let i = ((Number)(e_target1.textContent)) + 1; i < e.target.textContent; i++){\r\n");
      out.write("                        $(\"#date2_\"+i).css(\"background-color\", \"#FFDDDD\");\r\n");
      out.write("                    }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                dtemp = 0;\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        //달력 열기\r\n");
      out.write("        $(\"#calendar_date\").click(function(e){\r\n");
      out.write("            if($(\"#arrive_point\").val() == \"도착지\"){\r\n");
      out.write("                alert(\"도착지를 설정해주세요\");\r\n");
      out.write("            }\r\n");
      out.write("            else{ \r\n");
      out.write("                $(\"#calendar\").css(\"display\", \"inline-block\");\r\n");
      out.write("                $(\"#starting_point_serch\").css(\"display\", \"none\");\r\n");
      out.write("                $(\"#arrive_point_serch\").css(\"display\", \"none\");\r\n");
      out.write("                $(\"#personnel\").css(\"display\", \"none\");\r\n");
      out.write("                CDate.setMonth(CDate.getMonth()+1);\r\n");
      out.write("                let text = $.create_cal(2);\r\n");
      out.write("                $(\"#cal2\").html(text);\r\n");
      out.write("                CDate.setMonth(CDate.getMonth()-1);\r\n");
      out.write("                text = $.create_cal(1);\r\n");
      out.write("                $(\"#cal1\").html(text);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        //이전달 버튼\r\n");
      out.write("        $(\"#cal_pre\").click(function(e){\r\n");
      out.write("            let text = $.create_cal(2);\r\n");
      out.write("            $(\"#cal2\").html(text);\r\n");
      out.write("            CDate.setMonth(CDate.getMonth()-1); \r\n");
      out.write("            text = $.create_cal(1);\r\n");
      out.write("            $(\"#cal1\").html(text);\r\n");
      out.write("        })\r\n");
      out.write("        //다음달 버튼\r\n");
      out.write("        $(\"#cal_next\").click(function(e){\r\n");
      out.write("            CDate.setMonth(CDate.getMonth()+2);\r\n");
      out.write("            let text = $.create_cal(2);\r\n");
      out.write("            $(\"#cal2\").html(text);\r\n");
      out.write("            CDate.setMonth(CDate.getMonth()-1); \r\n");
      out.write("            text = $.create_cal(1);\r\n");
      out.write("            $(\"#cal1\").html(text);\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        //달력 선택버튼\r\n");
      out.write("        $(\"#date_select\").click(function(){\r\n");
      out.write("            let a = CDate.getFullYear().toString();\r\n");
      out.write("            let a2 = CDate.getFullYear().toString();\r\n");
      out.write("            let b = (CDate.getMonth()+1).toString();\r\n");
      out.write("            let b2 = (CDate.getMonth()+2).toString();\r\n");
      out.write("            let c = ((String)(e_target1.textContent));\r\n");
      out.write("            let c2 = ((String)(e_target2.textContent));\r\n");
      out.write("\r\n");
      out.write("            if(e_target1.className == \"date\"){\r\n");
      out.write("                b = (CDate.getMonth()+1).toString();\r\n");
      out.write("            }else if(e_target1.className == \"date2\"){\r\n");
      out.write("                b = (CDate.getMonth()+2).toString();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if(e_target2.className == \"date\"){\r\n");
      out.write("                b2 = (CDate.getMonth()+1).toString();\r\n");
      out.write("            }else if(e_target2.className == \"date2\"){\r\n");
      out.write("                b2 = (CDate.getMonth()+2).toString();\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if(b == 13){\r\n");
      out.write("                a = (CDate.getFullYear()+1).toString();\r\n");
      out.write("                b = 1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            if(b2 == 13){\r\n");
      out.write("                a2 = (CDate.getFullYear()+1).toString();\r\n");
      out.write("                b2 = 1;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            text1 = a+b+c;\r\n");
      out.write("            text2 = a2+b2+c2;\r\n");
      out.write("            textd1 = a + \".\" + b + \".\" +  c ;\r\n");
      out.write("            textd2 =  a2 + \".\" + b2 + \".\" + c2;\r\n");
      out.write("            date_flag = 1;\r\n");
      out.write("\r\n");
      out.write("            $(\"#minimumDate\").val(textd1);\r\n");
      out.write("            $(\"#maximumDate\").val(textd2);\r\n");
      out.write("            $(\"#calendar_date\").val(textd1 + \" ~ \" + textd2);\r\n");
      out.write("            $(\"#serch\").attr(\"disabled\", false).css(\"background-color\", \"#ff5000\");\r\n");
      out.write("            $(\"#calendar\").css(\"display\", \"none\");\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        //인원수 선택 버튼\r\n");
      out.write("        $(\"#person\").click(function(){\r\n");
      out.write("            if(date_flag == 0){\r\n");
      out.write("                alert(\"여정 및 일정을 먼저 선택해주세요\"); \r\n");
      out.write("            }\r\n");
      out.write("            else if(date_flag == 1){\r\n");
      out.write("            	$(\"#adultNumber\").val(adultNumber);\r\n");
      out.write("            	$(\"#childNumber\").val(childNumber);\r\n");
      out.write("            	$(\"#babyNumber\").val(babyNumber);\r\n");
      out.write("                $(\"#personnel\").css(\"display\", (\"inline-block\"));\r\n");
      out.write("                $(\"#p_start\").text($(\"#starting_point\").val());\r\n");
      out.write("                $(\"#p_startd\").text(textd1);\r\n");
      out.write("                $(\"#p_arrive\").text($(\"#arrive_point\").val());\r\n");
      out.write("                $(\"#p_arrived\").text(textd2);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        //인원수 처리 버튼\r\n");
      out.write("        //왼쪽(성인)\r\n");
      out.write("        let adultNumber = 1; //다음페이지로 가지고 갈 데이터 변수\r\n");
      out.write("        $(\"#left_text\").val(adultNumber);\r\n");
      out.write("        $(\"#left_down\").click(function(){\r\n");
      out.write("            --num;\r\n");
      out.write("            adultNumber = num;\r\n");
      out.write("            $(\"#left_text\").val(adultNumber);\r\n");
      out.write("            if(num == 0){\r\n");
      out.write("                $(\"#left_down\").attr(\"disabled\",true);\r\n");
      out.write("            }\r\n");
      out.write("            else if(num == 8){\r\n");
      out.write("                $(\"#left_up\").attr(\"disabled\",false);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        $(\"#left_up\").click(function(){\r\n");
      out.write("            ++num;\r\n");
      out.write("            adultNumber = num;\r\n");
      out.write("            $(\"#left_text\").val(adultNumber);\r\n");
      out.write("            if(num == 9){\r\n");
      out.write("                $(\"#left_up\").attr(\"disabled\",true);\r\n");
      out.write("            }\r\n");
      out.write("            else if(num == 1){\r\n");
      out.write("                $(\"#left_down\").attr(\"disabled\",false);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        //중앙(어린이)\r\n");
      out.write("        let childNumber = 0;	//다음페이지로 가지고 갈 데이터 변수\r\n");
      out.write("        $(\"#center_text\").val(childNumber);\r\n");
      out.write("        $(\"#center_down\").click(function(){\r\n");
      out.write("            --num;\r\n");
      out.write("            childNumber = num;\r\n");
      out.write("            $(\"#center_text\").val(childNumber);\r\n");
      out.write("            if(num == 0){\r\n");
      out.write("                $(\"#center_down\").attr(\"disabled\",true);\r\n");
      out.write("            }\r\n");
      out.write("            else if(num == 8){\r\n");
      out.write("                $(\"#center_up\").attr(\"disabled\",false);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        $(\"#center_up\").click(function(){\r\n");
      out.write("            ++num;\r\n");
      out.write("            childNumber = num;\r\n");
      out.write("            $(\"#center_text\").val(childNumber);\r\n");
      out.write("            if(num == 9){\r\n");
      out.write("                $(\"#center_up\").attr(\"disabled\",true);\r\n");
      out.write("            }\r\n");
      out.write("            else if(num == 1){\r\n");
      out.write("                $(\"#center_down\").attr(\"disabled\",false);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        //오른쪽(유아)\r\n");
      out.write("        let babyNumber = 0; //다음페이지로 가지고 갈 데이터 변수\r\n");
      out.write("        $(\"#right_text\").val(babyNumber);\r\n");
      out.write("        $(\"#right_down\").click(function(){\r\n");
      out.write("            --num;\r\n");
      out.write("            babyNumber = num;\r\n");
      out.write("            $(\"#right_text\").val(babyNumber);\r\n");
      out.write("            if(num == 0){\r\n");
      out.write("                $(\"#right_down\").attr(\"disabled\",true);\r\n");
      out.write("            }\r\n");
      out.write("            else if(num == 8){\r\n");
      out.write("                $(\"#right_up\").attr(\"disabled\",false);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("        $(\"#right_up\").click(function(){\r\n");
      out.write("            ++num;\r\n");
      out.write("            babyNumber = num;\r\n");
      out.write("            $(\"#right_text\").val(babyNumber);\r\n");
      out.write("            if(num == 9){\r\n");
      out.write("                $(\"#right_up\").attr(\"disabled\",true);\r\n");
      out.write("            }\r\n");
      out.write("            else if(num == 1){\r\n");
      out.write("                $(\"#right_down\").attr(\"disabled\",false);\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        //인원수 선택 버튼\r\n");
      out.write("        $(\"#select_personnel\").click(function(){\r\n");
      out.write("            let txt = \"\";\r\n");
      out.write("            $(\"#personnel\").css(\"display\", \"none\");\r\n");
      out.write("\r\n");
      out.write("            if($(\"#left_text\").val() > 0){\r\n");
      out.write("                txt = \"성인\" + ((String)($(\"#left_text\").val()));\r\n");
      out.write("            }\r\n");
      out.write("            if($(\"#center_text\").val() > 0){\r\n");
      out.write("                txt += \", 소아\" + $(\"#center_text\").val();\r\n");
      out.write("            }\r\n");
      out.write("            if($(\"#right_text\").val() > 0){\r\n");
      out.write("                txt += \", 유아\" + $(\"#right_text\").val();\r\n");
      out.write("            }\r\n");
      out.write("            $(\"#person\").val(txt);\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("        //닫기\r\n");
      out.write("        $(\".close\").click(function(e){\r\n");
      out.write("            $(\"#starting_point_serch\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#arrive_point_serch\").css(\"display\", \"none\");\r\n");
      out.write("            $(\"#calendar\").css(\"display\", \"none\");\r\n");
      out.write("        })\r\n");
      out.write("\r\n");
      out.write("        //항공권 검색 버튼\r\n");
      out.write("        $(\"#serch\").click(function(){\r\n");
      out.write("        	$(\"#info\").submit();\r\n");
      out.write("        })\r\n");
      out.write("        \r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 여행지 정보 출력 , 공지사항 스크롤 -->\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function(){\r\n");
      out.write("	  $('.main_imgs').bxSlider({\r\n");
      out.write("		adaptiveHeight: true,\r\n");
      out.write("	    maxSlides : 1,\r\n");
      out.write("	    minSlides : 3,\r\n");
      out.write("	    moveSlides : 1,\r\n");
      out.write("	    slideMargin : 20,\r\n");
      out.write("	    pause : 5000,\r\n");
      out.write("	    speed : 2000,\r\n");
      out.write("	    auto : true,\r\n");
      out.write("	    autoHover: true,\r\n");
      out.write("	    infiniteLoop : true,\r\n");
      out.write("	    pager : true, \r\n");
      out.write("	    stopAutoOnClick : true, \r\n");
      out.write("	    controls : false,\r\n");
      out.write("	    captions: true\r\n");
      out.write("	  })\r\n");
      out.write("      $('.banner_imgs').bxSlider({\r\n");
      out.write("        slideWidth : 1200,\r\n");
      out.write("        maxSlides : 5,\r\n");
      out.write("        minSlides : 3,\r\n");
      out.write("        moveSlides : 1,\r\n");
      out.write("        slideMargin : 20,\r\n");
      out.write("        pause : 5000,\r\n");
      out.write("        speed : 2000,\r\n");
      out.write("        auto : true,\r\n");
      out.write("        autoHover: true,\r\n");
      out.write("        infiniteLoop : true,\r\n");
      out.write("        pager : false, \r\n");
      out.write("        stopAutoOnClick : true, \r\n");
      out.write("        controls : true,\r\n");
      out.write("        captions: true\r\n");
      out.write("      })\r\n");
      out.write("      $('.banner_imgs2').bxSlider({\r\n");
      out.write("        slideWidth : 1200,\r\n");
      out.write("        slideHeight : 500,\r\n");
      out.write("        maxSlides : 1,\r\n");
      out.write("        minSlides : 1,\r\n");
      out.write("        moveSlides : 1,\r\n");
      out.write("        slideMargin : 20,\r\n");
      out.write("        pause : 5000,\r\n");
      out.write("        speed : 3000,\r\n");
      out.write("        auto : true,\r\n");
      out.write("        autoHover: true,\r\n");
      out.write("        infiniteLoop : true,\r\n");
      out.write("        pager : false, \r\n");
      out.write("        stopAutoOnClick : true, \r\n");
      out.write("        controls : false,\r\n");
      out.write("        captions: true,\r\n");
      out.write("        mode: 'vertical'\r\n");
      out.write("      })\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <!--전체 화면 컨테이너-->\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("        <!--표 예매-->\r\n");
      out.write("        <div id=\"ticketing\">\r\n");
      out.write("            <div id=\"ticketing_box\" style=\"position: relative; bottom: 60; z-index: 2;\">\r\n");
      out.write("                <nav id=\"way\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a id=\"round\" href=\"#\">왕복</a></li>\r\n");
      out.write("                        <li><a id=\"oneway\" href=\"#\">편도</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <div id=\"form_div\">\r\n");
      out.write("                    <form id=\"info\" action=\"flight/searchDepartFlight.do\" method=\"post\">\r\n");
      out.write("                        <input type=\"button\" id=\"starting_point\" value=\"출발지\">\r\n");
      out.write("                      	<input type=\"hidden\" id=\"departPointId\" name=\"departPointId\" value=\"\">\r\n");
      out.write("                        <input type=\"button\" id=\"swap\">\r\n");
      out.write("                        <input type=\"button\" id=\"arrive_point\" value=\"도착지\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"arrivedPointId\" name=\"arrivedPointId\" value=\"\">\r\n");
      out.write("                        <input type=\"button\" id=\"calendar_date\" name=\"calendar\" value=\"2022.11.20 ~ 2022.11.21\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"minimumDate\" name=\"minimumDate\" value=\"\">\r\n");
      out.write("                        <input type=\"hidden\" id=\"maximumDate\" name=\"maximumDate\" value=\"\">\r\n");
      out.write("                        <input type=\"button\" id=\"person\" name=\"passengerNumber\" value=\"성인1\">\r\n");
      out.write("                       	<input type=\"hidden\" id=\"adultNumber\" name=\"adultNumber\" value=\"1\">\r\n");
      out.write("                       	<input type=\"hidden\" id=\"childNumber\" name=\"childNumber\" value=\"0\">\r\n");
      out.write("                       	<input type=\"hidden\" id=\"babyNumber\" name=\"babyNumber\" value=\"0\">\r\n");
      out.write("                        <input type=\"button\" id=\"serch\" value=\"항공권 검색\" disabled>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"starting_point_serch\">\r\n");
      out.write("                    <nav id=\"dummy_serch\">\r\n");
      out.write("                        <img id=\"dummy_serch_img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/search.png\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"어디에서 출발하세요??\" onfocus=\"this.placeholder=''\" onblur=\"this.placeholder='어디에서 출발하세요??'\">\r\n");
      out.write("                        <img class=\"close\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/X.png\">\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <nav id=\"starting_point_list1\">\r\n");
      out.write("                    	<ul>\r\n");
      out.write("	                        <li>대한민국</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <nav id=\"starting_point_list2\">\r\n");
      out.write("                    	<ul>\r\n");
      out.write("	                    	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    	</ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"arrive_point_serch\">\r\n");
      out.write("                    <nav id=\"dummy_serch\">\r\n");
      out.write("                        <img id=\"dummy_serch_img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/search.png\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"어디로 여행가세요??\" onfocus=\"this.placeholder=''\" onblur=\"this.placeholder='어디로 여행가세요??'\">\r\n");
      out.write("                        <img class=\"close\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/X.png\">\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <nav id=\"arrive_point_list1\">\r\n");
      out.write("                    	<ul>\r\n");
      out.write("	                        <li>대한민국</li>\r\n");
      out.write("                    	</ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                    <nav id=\"arrive_point_list2\">\r\n");
      out.write("	                    <ul>\r\n");
      out.write("	                    	");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    	</ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 달력 -->\r\n");
      out.write("            <div id=\"calendar\">\r\n");
      out.write("                <div id=\"cal1_div\">\r\n");
      out.write("                    <button id=\"cal_pre\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/left_btn.png\"></button>\r\n");
      out.write("                    <a id=\"cal1_year\"></a>\r\n");
      out.write("                    <a id=\"cal1_month\"></a>\r\n");
      out.write("                    <nav id=\"cal1\"></nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"cal2_div\">\r\n");
      out.write("                    <button id=\"cal_next\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/right_btn.png\"></button>\r\n");
      out.write("                    <a id=\"cal2_year\"></a>\r\n");
      out.write("                    <a id=\"cal2_month\"></a>\r\n");
      out.write("                    <nav id=\"cal2\"></nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button id=\"date_select\">선택</button>\r\n");
      out.write("                <img class=\"close\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/X.png\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--인원수 선택-->\r\n");
      out.write("            <div id=\"personnel\">\r\n");
      out.write("                <div id=\"personnel_header\">\r\n");
      out.write("                    <div id=\"personnel_header_left\">\r\n");
      out.write("                        <nav id=\"p_start\"></nav>\r\n");
      out.write("                        <nav id=\"p_startd\"></nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/arrow.png\">\r\n");
      out.write("                    <div id=\"personnel_header_right\">\r\n");
      out.write("                        <nav id=\"p_arrive\"></nav>\r\n");
      out.write("                        <nav id=\"p_arrived\"></nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"personnel_body\">\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <div id=\"personnel_body_left\">\r\n");
      out.write("                        <div class=\"body_text_title\">성인</div>\r\n");
      out.write("                        <div class=\"body_text_content\">\r\n");
      out.write("                        <nav>12세 이상</nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"body_button_left\">\r\n");
      out.write("                            <button id=\"left_down\">-</button>\r\n");
      out.write("                            <input type=\"text\" id=\"left_text\" value=\"1\" readonly>\r\n");
      out.write("                            <button id=\"left_up\">+</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"personnel_body_center\">\r\n");
      out.write("                        <div class=\"body_text_title\">소아</div>\r\n");
      out.write("                        <div class=\"body_text_content\">\r\n");
      out.write("                            <nav>12세 이상</nav>\r\n");
      out.write("                            <nav>(최초 출발일 기준)</nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"body_button_center\">\r\n");
      out.write("                            <button id=\"center_down\" disabled>-</button>\r\n");
      out.write("                            <input type=\"text\" id=\"center_text\" value=\"0\" readonly>\r\n");
      out.write("                            <button id=\"center_up\">+</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"personnel_body_right\">\r\n");
      out.write("                        <div class=\"body_text_title\">유아</div>\r\n");
      out.write("                        <div class=\"body_text_content\">\r\n");
      out.write("                            <nav>생후 14일 이상~만 2세 미만</nav>\r\n");
      out.write("                            <nav>(만 24개월 미만/최종 탑승일 기준)</nav>   \r\n");
      out.write("                            <nav>유아의 여정이 동반 성인과 일치하지 않으면</nav>\r\n");
      out.write("                            <nav>환불 후 재구매해야 합니다.</nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"body_button_right\">\r\n");
      out.write("                            <button id=\"right_down\" disabled>-</button>\r\n");
      out.write("                            <input type=\"text\" id=\"right_text\" value=\"0\" readonly>\r\n");
      out.write("                            <button id=\"right_up\">+</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button id=\"select_personnel\">선택</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  <div id=\"main_banner\">\r\n");
      out.write("  	<div class=\"main_imgs\">\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mainImg.jpg\" width=\"1700px\" height=\"500px\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/Winter.jpg\" width=\"1700px\" height=\"500px\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/busan.jpg\" width=\"1700px\" height=\"500px\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/m4.jpg\" width=\"1700px\" height=\"500px\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("  	</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"f_banner\">\r\n");
      out.write("    <h2>추천 항공권</h2>\r\n");
      out.write("    <div class=\"banner_imgs\">\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/bs.jpg\">\r\n");
      out.write("          <p id=\"route\"><strong>서울(인천) - 부산</strong><br>\r\n");
      out.write("            <sup>편도총액</sup> <b>62,100원~</b><br>\r\n");
      out.write("            <span>2022.12.15~2023.01.15</span>\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/cc.jpg\">\r\n");
      out.write("          <p id=\"route\"><strong>서울(인천) - 충청도</strong><br>\r\n");
      out.write("            <sup>편도총액</sup> <b>49,100원~</b><br>\r\n");
      out.write("            <span>2022.12.24~2023.02.11</span>\r\n");
      out.write("          </p>\r\n");
      out.write("        </a> \r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/kj.jpg\">\r\n");
      out.write("          <p id=\"route\"><strong>서울(인천) - 경주</strong><br>\r\n");
      out.write("            <sup>편도총액</sup> <b>55,200원~</b><br>\r\n");
      out.write("            <span>2022.11.29~2023.01.19</span>\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/jj.jpg\">\r\n");
      out.write("          <p id=\"route\"><strong>서울(인천) - 제주</strong><br>\r\n");
      out.write("            <sup>편도총액</sup> <b>66,000원~</b><br>\r\n");
      out.write("            <span>2023.1.16~2023.02.23</span>\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/kw.jpg\">\r\n");
      out.write("          <p id=\"route\"><strong>서울(인천) - 강원도</strong><br>\r\n");
      out.write("            <sup>편도총액</sup> <b>45,700원~</b><br>\r\n");
      out.write("            <span>2022.11.23~2023.02.09</span>\r\n");
      out.write("          </p>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<div id=\"s_banner\">\r\n");
      out.write("    <h2>공지사항</h2>\r\n");
      out.write("    <div class=\"banner_imgs2\">\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/notice01.jpg\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/qna01.jpg\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/call01.jpg\">\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /mainPage.jsp(729,22) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/mainPage.jsp(729,22) '${airportList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${airportList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /mainPage.jsp(729,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("airportList");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	                    		<div class=\"start\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${airportList.airportName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&emsp;");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${airportList.airportCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("	                    	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /mainPage.jsp(749,22) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/mainPage.jsp(749,22) '${airportList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${airportList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /mainPage.jsp(749,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("airportList");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	                    		<div class=\"arrive\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${airportList.airportName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&emsp;");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${airportList.airportCode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("	                    	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
