/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-12-02 03:44:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class userInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/hyuck/Spring/mini/planeproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PlaneTripProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/hyuck/Spring/mini/planeproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PlaneTripProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668733234630L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>마이페이지</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Jua&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("	hr { border : 1px solid #d2d2d2;}\r\n");
      out.write("	#r_arrow { width : 10px; height : 15px; margin-right : 15px; margin-left : 15px;}\r\n");
      out.write("	#p_location { \r\n");
      out.write("		width : 100%;\r\n");
      out.write("		height : 50px;\r\n");
      out.write("		text-align : center;\r\n");
      out.write("		font-weight : bold;\r\n");
      out.write("		color:#848484; \r\n");
      out.write("		background-color :#d2d2d2; \r\n");
      out.write("		margin-top : 15px; \r\n");
      out.write("		margin-bottom : 15px; \r\n");
      out.write("		font-size : 1.1em;\r\n");
      out.write("		border-top : 2px solid orange;\r\n");
      out.write("		border-bottom : 2px solid orange;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("    body { background-color : #F6F6F6;}\r\n");
      out.write("    /* 전체 컨테이너 */\r\n");
      out.write("   	#mypage_container{ width: 100%; display: inline-block; text-align: center; margin-bottom : 280px;}\r\n");
      out.write("    /* 페이지 제목 */\r\n");
      out.write("    #page_name{ width: 1000px; display: inline-block; font-family: 'Jua'; font-size: xx-large; \r\n");
      out.write("        text-align: left; margin-top: 40px;}\r\n");
      out.write("    #reservation{ width: 1000px; display: inline-block;}\r\n");
      out.write("    #reservation_name{ text-align: left; font-family: 'Jua';}\r\n");
      out.write("\r\n");
      out.write("    /* 예약현황부분 */\r\n");
      out.write("    #reservation_table{ width: 1000px; border: 1px solid #bebebe;}\r\n");
      out.write("    #reservation_table table{ width: 100%;  border-collapse:collapse; font-family: 'Jua';}\r\n");
      out.write("    #reservation_table th, #reservation_table td{ border: 1px solid #bebebe;}\r\n");
      out.write("    #reservation_table th{ width: 16.5%; height: 50px; background-color: #dcdcdc; }\r\n");
      out.write("    #reservation_table td{ height: 30px; text-align: center;}\r\n");
      out.write("\r\n");
      out.write("    /* 회원정보 */\r\n");
      out.write("    #guest_info{  width: 1000px; height: 10px; display: inline-block; margin-top: 30px;}\r\n");
      out.write("    #guest_info_name{  text-align: left; font-family: 'Jua';}\r\n");
      out.write("    #info1{ width: 450px; height: 200px; background-color: #dcdcdc; float: left; position: relative;}\r\n");
      out.write("    #info2{ width: 450px; height: 200px; background-color: #dcdcdc; float: right;}\r\n");
      out.write("\r\n");
      out.write("    #info1 img{ width: 150px; height: 180px; margin-left: 20px; margin-top: 10px; float: left;}\r\n");
      out.write("    #info_id_title{ position: absolute; left: 190px; top: 60px;}\r\n");
      out.write("    #info_id{  position: absolute; left: 290px; top: 60px;}\r\n");
      out.write("    #correction_btn{ width: 100px; height: 30px; position: absolute; top: 120px; left: 260px;}\r\n");
      out.write("    #withdrawal_btn{ border: none; background: none; position: absolute; bottom: 5px; right: 5px; }\r\n");
      out.write("    \r\n");
      out.write("    #info2_div{ margin-left: 80px;}\r\n");
      out.write("    .info_head{ width: 30%; height: 10px; float: left; text-align: left; margin-top: 30px;}\r\n");
      out.write("    #info_name{ width: 50%; height: 10px; float: left; text-align: left; margin-top: 30px; margin-left: 30px;}\r\n");
      out.write("    #info_birth{ width: 50%; height: 10px; float: left; text-align: left; margin-top: 30px; margin-left: 30px;}\r\n");
      out.write("    #info_address{ width: 50%; height: 10px; float: left; text-align: left; margin-top: 30px; margin-left: 30px;}\r\n");
      out.write("    #info_ph{ width: 50%; height: 10px; float: left; text-align: left; margin-top: 30px; margin-left: 30px;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    a:link { color: black;}\r\n");
      out.write("    a:visited { color: black;}\r\n");
      out.write("    a:hover { color: black;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("        //innerHtml에 넣는 내용\r\n");
      out.write("        let reservation_html = \"<table><tr><th>예약번호</th><th>탑승일</th><th>탑승구간</th><th>탑승자</th><th>예약일</th><th>예약/취소여부</th></tr>\" \r\n");
      out.write("        let personnal_num = 3;              //예약 인원수(현재는 임의로 지정), 후에 넣을때는 (Number)로 형변환 해서 넣어주세요\r\n");
      out.write("\r\n");
      out.write("        $(\"#headers\").load(\"../asdf/header.html\");\r\n");
      out.write("\r\n");
      out.write("        //예약현황 테이블 만드는부분(내용이 들어가는 부분을 a태그에 각각 아이디를 줬음)\r\n");
      out.write("                                //ex)reservation_num1, reservation_num2\r\n");
      out.write("                                //넣을때 for문 돌려서 아이디 -> innerHtml값 건드시면 쉽게 넣으실거에요\r\n");
      out.write("        for(let i = 1; i <= personnal_num; i++){\r\n");
      out.write("            reservation_html += \"<tr><td><a id='reservation_num\"+i+\"'>asdf123</a></td>\";\r\n");
      out.write("            reservation_html += \"<td><a id='depart_date\"+i+\"'>2022.11.27</a></td>\";\r\n");
      out.write("            reservation_html += \"<td><a id='section\"+i+\"'>서울(김포) - 제주</a></td>\";       //innerHtml넣을때 '출발지' + '-' + '도착지'해야함\r\n");
      out.write("            reservation_html += \"<td><a id='guest_name\"+i+\"'>ㅁㄴㅇㄹ</a></td>\";\r\n");
      out.write("            reservation_html += \"<td><a id='reservation_date\"+i+\"'>2022.11.27</a></td>\";\r\n");
      out.write("            reservation_html += \"<td><a id='cancellation\"+i+\"' class=cancellation>예약</a></td></tr>\";\r\n");
      out.write("        }\r\n");
      out.write("        reservation_html += \"</table>\";\r\n");
      out.write("        //$(\"#reservation_table\").html();\r\n");
      out.write("        //$(\"#reservation_table\").html(reservation_html);\r\n");
      out.write("\r\n");
      out.write("        //임의로 한개 취소로 바꿈           나중에 지우세요\r\n");
      out.write("        $(\"#cancellation2\").html(\"취소\");\r\n");
      out.write("\r\n");
      out.write("        //글자가 예약일때는 파랑 취소일때는 빨강\r\n");
      out.write("        for(let i = 1; i <= personnal_num; i++){\r\n");
      out.write("            if($(\"#cancellation\"+i).html() == \"예약\"){\r\n");
      out.write("                $(\"#cancellation\"+i).css(\"color\",\"blue\");\r\n");
      out.write("            }else if($(\"#cancellation\"+i).html() == \"취소\"){\r\n");
      out.write("                $(\"#cancellation\"+i).css(\"color\",\"red\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("   })\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("   	<div id=\"mypage_container\">\r\n");
      out.write("   		<input type=\"hidden\" id=\"updateMsg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${updateMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        <!--타이틀-->\r\n");
      out.write("        <div id=\"p_location\">\r\n");
      out.write("			<div style=\"display: inline-block;text-align:left; width:1070px; margin-top : 14px;\">\r\n");
      out.write("				<span>홈<img id=\"r_arrow\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/r_arrow.png\">마이페이지</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("        <div id=\"page_name\">마이페이지</div>\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <!--예약현황-->\r\n");
      out.write("        <div id=\"reservation\">\r\n");
      out.write("            <div id=\"reservation_name\">예약현황(예약 및 취소내역)</div>\r\n");
      out.write("            <!--div만 만들어두고 스크립트에서 인원수에 따라 for문 돌려 표로 작성-->\r\n");
      out.write("            <div id=\"reservation_table\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<tr><th>예약번호</th><th>탑승일</th><th>출발 -> 도착</th><th>도착시간</th><th>탑승자</th><th>예약/취소여부</th></tr>\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--회원정보-->\r\n");
      out.write("        <div id=\"guest_info\">\r\n");
      out.write("            <div id=\"guest_info_name\">회원 정보</div>\r\n");
      out.write("            <div id=\"info1\">\r\n");
      out.write("                <div><img src=\"/images/person.png\"></div>\r\n");
      out.write("                <div id=\"info_id_title\">아이디</div>\r\n");
      out.write("                <div id=\"info_id\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("                <button id=\"correction_btn\" onclick=\"location.href='/Account/updateInfo.do';\">회원정보 수정</button>\r\n");
      out.write("                <a href=\"/Account/quit.do\" id=\"withdrawal_btn\">회원탈퇴</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"info2\">\r\n");
      out.write("                <div id=\"info2_div\">\r\n");
      out.write("                    <div class=\"info_head\">성명</div>\r\n");
      out.write("                    <div id=\"info_name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.fullName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"info_head\">생년월일</div>\r\n");
      out.write("                    <div id=\"info_birth\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.birthDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"info_head\">전화번호</div>\r\n");
      out.write("                    <div id=\"info_ph\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                    <div class=\"info_head\">주소</div>\r\n");
      out.write("                    <div id=\"info_address\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   $(function() {\r\n");
      out.write("		//회원정보 수정 실패 시 메시지 출력\r\n");
      out.write("		if($(\"#updateMsg\").val() != \"\" && $(\"#updateMsg\").val() != null) {\r\n");
      out.write("			alert($(\"#updateMsg\").val());\r\n");
      out.write("		}\r\n");
      out.write("   });\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/mypage/userInfo.jsp(130,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/mypage/userInfo.jsp(130,5) '${myReservation.myList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${myReservation.myList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/mypage/userInfo.jsp(130,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("reservation");
      // /WEB-INF/views/mypage/userInfo.jsp(130,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<tr>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ myReservation.myList[status.index].reservationId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ myReservation.myList[status.index].departDatetime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ myReservation.myList[status.index].AirportDptNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" -> ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${myReservation.myList[status.index].AirportArvNm }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ myReservation.myList[status.index].arrivalDatetime }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ myReservation.myList[status.index].passengerName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("						<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ myReservation.myList[status.index].updateReservation }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("					</tr>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
