/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-12-01 19:15:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("<style>\r\n");
      out.write("	body { background-color : #F6F6F6;}\r\n");
      out.write("	\r\n");
      out.write("	#r_arrow { width : 10px; height : 15px; margin-right : 15px; margin-left : 15px;}\r\n");
      out.write("	#login_img { width : 40px; height : 40px; margin-bottom : 28px; margin-right : 60px;}\r\n");
      out.write("	#p_location { \r\n");
      out.write("		width : 100%;\r\n");
      out.write("		height : 50px;\r\n");
      out.write("		text-align : center;\r\n");
      out.write("		font-weight : bold;\r\n");
      out.write("		color:#848484; \r\n");
      out.write("		background-color :#d2d2d2; \r\n");
      out.write("		margin-top : 15px; \r\n");
      out.write("		margin-bottom : 15px; \r\n");
      out.write("		font-size : 1.1em;\r\n");
      out.write("		border-top : 2px solid orange;\r\n");
      out.write("		border-bottom : 2px solid orange;\r\n");
      out.write("	}\r\n");
      out.write("	 \r\n");
      out.write("	.form-wrapper {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		justify-content: center;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("		margin-bottom : 80px;\r\n");
      out.write("		margin-top : 80px;\r\n");
      out.write("	}\r\n");
      out.write("	hr { border : 1px solid #d2d2d2;}\r\n");
      out.write("	h1 { text-align: center; margin-bottom: 50px;}\r\n");
      out.write("	\r\n");
      out.write("	#loginForm {\r\n");
      out.write("		width: 300px;\r\n");
      out.write("		text-align: center;\r\n");
      out.write("		border : 2px solid #d2d2d2;\r\n");
      out.write("		padding-left : 200px;\r\n");
      out.write("		padding-right : 200px;\r\n");
      out.write("		padding-top : 40px;\r\n");
      out.write("		padding-bottom : 55px;\r\n");
      out.write("		border-radius : 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#loginForm .label-wrapper {\r\n");
      out.write("		margin-top: 20px;\r\n");
      out.write("		margin-bottom : 10px;\r\n");
      out.write("		display: flex;\r\n");
      out.write("		justify-content: space-between;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#loginForm input {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		background-color : #F6F6F6;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#loginForm div {\r\n");
      out.write("		display: flex;\r\n");
      out.write("		align-items: center;\r\n");
      out.write("	}\r\n");
      out.write("	.form-wrapper input { border : 0px; height: 30px;} \r\n");
      out.write("	.btn_s { width: 300px; height: 50px; border-radius: 4px; border : 0px; background-color: #787878; color: white; font-size: 1.0em;}\r\n");
      out.write("	#find { text-align: center; justify-content: center; margin-top: 15px; font-size : 0.9em;}\r\n");
      out.write("	#a_find { margin-left: 30px; margin-right: 30px;}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    a:link { color: black; text-decoration: none;}\r\n");
      out.write("    a:visited { color: black; text-decoration: none;}\r\n");
      out.write("    a:hover { color: black; text-decoration: none;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div id=\"p_location\">\r\n");
      out.write("		<div style=\"display: inline-block;text-align:left; width:1070px; margin-top : 14px;\">\r\n");
      out.write("			<span>홈<img id=\"r_arrow\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/r_arrow.png\">로그인</span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"form-wrapper\">\r\n");
      out.write("		<form id=\"loginForm\">\r\n");
      out.write("			<input type=\"hidden\" id=\"joinMsg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${joinMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<img id=\"login_img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/login.png\">\r\n");
      out.write("				<h1>로그인</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"label-wrapper\">\r\n");
      out.write("				<label for=\"email\">아이디</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"text\" id=\"email\" name=\"email\" required>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<div class=\"label-wrapper\">\r\n");
      out.write("				<label for=\"password\">비밀번호</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<input type=\"password\" id=\"password\" name=\"password\" required>\r\n");
      out.write("			<hr>\r\n");
      out.write("			<div id=\"find\">\r\n");
      out.write("				<a href=\"\" onclick=\"window.open('/Account/findId.do','아이디 찾기', 'width=500px, height=500px');return false\" id =\"a_find\">아이디 찾기</a>\r\n");
      out.write("				<a href=\"\" onclick=\"window.open('/Account/findPassword.do','비밀번호 찾기', 'width=500px, height=530px');return false\" id =\"a_find\">비밀번호 찾기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style=\"display: block; margin: 8px auto; margin-top : 60px;\">\r\n");
      out.write("				<button type=\"button\" id=\"btnLogin\" class=\"btn_s\">로그인</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style=\"display: block; margin: 5px auto;\">\r\n");
      out.write("				<button type=\"button\" class=\"btn_s\" onclick=\"location.href='/Account/join.do';\">회원가입</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			//회원가입 성공 시 메시지 출력\r\n");
      out.write("			if($(\"#joinMsg\").val() != \"\" && $(\"#joinMsg\").val() != null) {\r\n");
      out.write("				alert($(\"#joinMsg\").val());\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			//로그인 시 아이디나 비밀번호가 틀렸을 경우에\r\n");
      out.write("			$(\"#btnLogin\").on(\"click\", function() {\r\n");
      out.write("				console.log(\"로그인 시도 중입니다........=======\");\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					url: \"/Account/login.do\",\r\n");
      out.write("					type: \"post\",\r\n");
      out.write("					data: $(\"#loginForm\").serialize(),\r\n");
      out.write("					success: function(obj) {\r\n");
      out.write("						console.log(obj);\r\n");
      out.write("						//id 체크\r\n");
      out.write("						if(obj == \"idFail\") {\r\n");
      out.write("							alert(\"존재하지 않는 아이디입니다.\");\r\n");
      out.write("							$(\"#email\").focus();\r\n");
      out.write("							return;\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("						//pw 체크\r\n");
      out.write("						if(obj ==\"pwFail\") {\r\n");
      out.write("							alert(\"비밀번호가 틀렸습니다. 비밀번호를 확인해주세요.\");\r\n");
      out.write("							$(\"#password\").focus();\r\n");
      out.write("							return;\r\n");
      out.write("						}\r\n");
      out.write("						\r\n");
      out.write("						//로그인 처리\r\n");
      out.write("						location.href=\"/mainPage.do\";\r\n");
      out.write("						\r\n");
      out.write("					},\r\n");
      out.write("					error: function(e) {\r\n");
      out.write("						console.log(e);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
